### ISSUE TITLE
Updated textarea contents are not always reflected in underlying interface (eg. FastMail)

### ISSUE THREAD

**Issue by lamby** [WayneD/TextEditAid#1]
At its heart, TextAid executes the following in order to update the value in the underlying `<textarea>` element:

```
      ta.value = request.text;
```

However, for some 'advanced' Javascript applications, while this might seem to update the page, some *underlying* data structure is not updated in turn. This results in some confusion as pressing, say, 'Save' does not use the new, edited, value. One example is Fastmail -- due to some quirk/feature of their Javascript framework, if you update the textarea's `value` attribute whilst writing an email, Fastmail's own idea of the contents of that email is not changed. If you then press send, the 'old' value is then sent. You can force some kind of sync between the visual interface and the underlying value by manually making a change (eg. adding a newline and then removing it), but clearly this is a bit clunky. I've tried adding a few things like `ta.dispatchEvent(new Event('change'))` but to no avail. Any ideas?

**Comment by WayneD** [comment]
I'd suggest that you right-click the textarea, choose "inspect" and then use the "Event Listeners" tab near the right side to see what listeners are active for the textarea. If you also make a note of the element's id name, you can then switch to the console tab and try some of the event triggers you saw. They might be listening to keydown/keyup or something like that.  It's surprising that faking a change event didn't work.

**Comment by lamby** [comment]
Thanks for the tips but alas they match what I have already tried. As in, I've been doing things like:

```
ta = document.getElementById("v368-input");
ta.value = "some new value simulating textaid"
ta.dispatchEvent(new Event('change', {'bubbles': true}))
```

Regarding the event listeners, the framework seems to wrap everything, so it's difficult to know what is going on:

![image](https://user-images.githubusercontent.com/133209/159883878-d9fc8771-7f33-416c-ba24-2e057cced8d4.png)

**Comment by WayneD** [comment]
One possible avenue of investigation is to see how that page handles a paste event.  Trying to simulate that interaction when updating the field might be helpful.

I wonder if [text-aid-too](https://github.com/smblott-github/text-aid-too#text-aid-too) might have solved this already? That looks to be a more extensive setup than the simple code in my extension.

**Comment by lamby** [comment]
I wasn't aware of `text-aid-too` - thanks for that. However, I think it essentially does the same thing at it's core; as in, it [sets the value using `element.value = updated_value`](https://github.com/smblott-github/text-aid-too/blob/master/chrome-extension/foreground.coffee#L28), although there is a different codepath if the element is HTML or similar (which is not the case for me).

Alas just spent some time with the paste event, but to no avail. Maybe their javascript is just being too indirect or they have their own event loop or something?
